columnSuffix: jfhayfau
contentColumnType: string
fieldGroup: 734bb3f1-97ed-4c94-8234-b4002833597e # Common
handle: category
instructions: null
name: Kategorija
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'notes and stories'
        -
          - value
          - 'NOTES AND STORIES'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - artcicle
        -
          - value
          - ARTICLES
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - podcast
        -
          - value
          - PODCASTS
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
