fieldLayouts:
  995ec655-9e4a-4d09-9f6c-08b0d1156cb1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: ''
            type: craft\fieldlayoutelements\Heading
            uid: e1577a33-c94c-4d84-a7c8-4393a2f55cf2
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 22e4ffe4-43a5-4ac4-8df2-39dbed4c2a95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f7de5eb-1b48-4f02-8088-a464aeea88cd # Slika
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6570817c-2b15-42de-84ae-118c698674e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e8440175-43c0-41bd-92a3-fdac6020477c # Alt text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08504ab4-8845-42fd-8251-7e2bb64eb1c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f3d0073-5528-4253-b49e-0fc5e6d97441 # Rich text
            instructions: null
            label: Text
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd80c569-ca2b-47aa-a524-85c8aa8b1aaf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 517591a8-ff67-4a2d-9030-b017777f8d19 # Kategorija
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78b03e4f-5252-4280-9243-7fdf87206879
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9744b394-7f5b-4f3f-97ed-1061c9129eb2 # seo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3d163f2-842c-4c5a-9a45-72afc2930249
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4530a870-8e66-4589-899e-879ff79b6dbc
        userCondition: null
handle: default
hasTitleField: true
name: 'Notes and Stories'
section: e9b86cb5-7af9-4e68-bde6-8c598884aaf9 # Notes
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
