baseUrl: 'https://beta.kinoklub.si'
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Kino klub'
primary: true
siteGroup: a5095b5e-8a24-4f7f-bb02-26be023077b2 # Kino klub
sortOrder: 1
