fieldLayouts:
  6251ea77-686c-41e2-ae59-4eaec6d0458e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 301a6e28-5153-4bb7-af84-f73146831cc2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c54c9b4-f5a0-404c-acb3-318943b01ddb
        userCondition: null
fs: assets
handle: img
name: img
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
