fieldLayouts:
  a7216265-4694-42c2-8af2-276e72eaf16e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0f5b983c-5f43-485f-b429-0afcf215e7c8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 974fa045-da21-4ee5-aeb6-c4621560fbd2
        userCondition: null
fs: assets
handle: notesAndStories
name: 'Notes and stories'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
