columnSuffix: jfhayfau
contentColumnType: string
fieldGroup: 734bb3f1-97ed-4c94-8234-b4002833597e # Common
handle: category
instructions: null
name: Kategorija
searchable: true
settings:
  options:
    -
      __assoc__:
        -
          - label
          - postcard
        -
          - value
          - postcards
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - artcicle
        -
          - value
          - articles
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - video
        -
          - value
          - video
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
