columnSuffix: fijiecvz
contentColumnType: text
fieldGroup: 734bb3f1-97ed-4c94-8234-b4002833597e # Common
handle: naslov
instructions: null
name: Naslov
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: test
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
