columnSuffix: zvnlzusu
contentColumnType: string(100)
fieldGroup: 734bb3f1-97ed-4c94-8234-b4002833597e # Common
handle: place
instructions: null
name: Place
searchable: true
settings:
  byteLimit: null
  charLimit: 25
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
