columnSuffix: oqtyryrx
contentColumnType: text
fieldGroup: 734bb3f1-97ed-4c94-8234-b4002833597e # Common
handle: seo
instructions: 'Prosim podrobno izpolni, pomembno za vsako stran in jezik!'
name: seo
searchable: false
settings:
  description: 'A community of fellow motion picture lovers. Join us.'
  hideSocial: ''
  robots:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  socialImage:
    - '515'
  suffixAsPrefix: null
  title:
    -
      __assoc__:
        -
          - key
          - '2'
        -
          - locked
          - '0'
        -
          - template
          - 'Kino Klub'
    -
      __assoc__:
        -
          - key
          - b5j
        -
          - locked
          - '0'
        -
          - template
          - ' | {title}'
  titleSuffix: null
translationKeyFormat: null
translationMethod: language
type: ether\seo\fields\SeoField
