columnSuffix: yiwjnvjt
contentColumnType: text
fieldGroup: 734bb3f1-97ed-4c94-8234-b4002833597e # Common
handle: text
instructions: text
name: Vsebina
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: text
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
