dateModified: 1681371931
elementSources:
  craft\elements\Asset:
    -
      disabled: false
      key: 'volume:369e78c2-5589-40bf-b0bd-f7c8b9b2e955' # img
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
        - currentUsage
        - imageSize
      type: native
    -
      key: 'folder:268f63d7-06c2-4f44-8979-7308f68780d8'
      type: native
  craft\elements\Entry:
    -
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: ''
      type: heading
    -
      disabled: false
      key: 'section:e9b86cb5-7af9-4e68-bde6-8c598884aaf9' # Notes
      tableAttributes:
        - postDate
        - link
        - 'field:6f7de5eb-1b48-4f02-8088-a464aeea88cd' # Slika
        - 'field:517591a8-ff67-4a2d-9030-b017777f8d19' # Kategorija
        - dateUpdated
      type: native
    -
      disabled: false
      key: 'section:4afffa94-3642-4081-8cf0-0b281a97608b' # Events
      tableAttributes:
        - postDate
        - expiryDate
        - 'field:6f7de5eb-1b48-4f02-8088-a464aeea88cd' # Slika
        - 'field:0e562f94-5806-4803-bd62-64df37c4d6cf' # Date
        - 'field:1d09924c-7d8b-4c7b-bd9a-26a1510cd435' # Place
        - uri
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:3d596aee-6653-4770-a869-2adcf68e8a4f' # Projects
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: ''
      type: heading
    -
      disabled: false
      key: 'single:4b30886b-a63c-4f1a-998a-b2ef3d2b9f95' # Home
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      disabled: false
      key: 'single:4f541f05-c78e-43df-ba73-556c39ed5e4a' # About
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: ''
      type: heading
email:
  fromEmail: andrej7.cop@gmail.com
  fromName: 'Kino Klub'
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  img:
    hasUrls: true
    name: img
    settings:
      path: '@webroot/img'
    type: craft\fs\Local
    url: '@web/img'
meta:
  __names__:
    0e562f94-5806-4803-bd62-64df37c4d6cf: Date # Date
    1d09924c-7d8b-4c7b-bd9a-26a1510cd435: Place # Place
    3d596aee-6653-4770-a869-2adcf68e8a4f: Projects # Projects
    4afffa94-3642-4081-8cf0-0b281a97608b: Events # Events
    4b30886b-a63c-4f1a-998a-b2ef3d2b9f95: Home # Home
    4f541f05-c78e-43df-ba73-556c39ed5e4a: About # About
    5d67afcb-a40e-4d38-8b10-4423c1ba48a4: Naslov # Naslov
    6f7de5eb-1b48-4f02-8088-a464aeea88cd: Slika # Slika
    7dff5ce0-6641-40f0-926b-8bd7f905d8bf: 'Kino Klub SI' # Kino Klub SI
    7f3d0073-5528-4253-b49e-0fc5e6d97441: 'Rich text' # Rich text
    8b6fcde2-6dc2-4235-8257-f26af6b76a38: About # About
    9b7967d1-ab44-43c1-8617-27cc29600d25: 'Tip dogodka' # Tip dogodka
    12b23949-ae49-4d68-a14e-231270421b86: Home # Home
    17dfc7be-7af9-4875-ba4b-9ed7942d1a68: Opis # Opis
    47ab79f6-6159-4ddf-a6e3-22bee591def8: Banner_desktop # Banner_desktop
    71f1e1a8-6334-4c4d-9bfc-4c60fea6a590: Project # Project
    369e78c2-5589-40bf-b0bd-f7c8b9b2e955: img # img
    548d1972-4fd4-483a-9f1e-722e249ba366: 'Kino Klub EN' # Kino Klub EN
    637e8647-69ab-4ca9-8697-2fc85ae48e53: Time # Time
    734bb3f1-97ed-4c94-8234-b4002833597e: Common # Common
    9744b394-7f5b-4f3f-97ed-1061c9129eb2: seo # seo
    13206bce-4ea7-40c9-86fc-36ff7a728d7e: Banner_mobile # Banner_mobile
    517591a8-ff67-4a2d-9030-b017777f8d19: Kategorija # Kategorija
    a5095b5e-8a24-4f7f-bb02-26be023077b2: 'Kino klub' # Kino klub
    b6417f85-8d11-44f0-ab58-66f5733257d8: Events # Events
    e9b86cb5-7af9-4e68-bde6-8c598884aaf9: Notes # Notes
    e8440175-43c0-41bd-92a3-fdac6020477c: 'Alt text' # Alt text
    ec752501-2740-4382-afb1-396107a872da: 'Notes and Stories' # Notes and Stories
    fb8cea6e-566f-4bc2-9aa9-8b36e1f99879: Embed # Embed
plugins:
  assetusage:
    edition: standard
    enabled: false
    schemaVersion: 2.0.0
  craft-recaptcha:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      secretKey: 6LedrIIlAAAAAHvb5INOZ8MDmFtdyAIlIugr1OHD
      siteKey: 6LedrIIlAAAAAISRihmnW9uogL_vwSIg1R_0F_D0
      threshold: '1.0'
      validateContactForm: ''
      validateUsersRegistration: ''
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: true
      redirectToEntry: true
  newsletter:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      adapterType: juban\newsletter\adapters\Mailjet
      adapterTypeSettings:
        __assoc__:
          -
            - apiKey
            - 5cde44fa54be9b8aa7e9e14185ba6926
          -
            - apiSecret
            - 7b4fa5aac0f130f1512f3aa22dab185a
          -
            - listId
            - '10265280'
      recaptchaEnabled: true
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: 'A community of fellow motion picture lovers. Join us.'
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: '1'
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '10000'
      sitemapName: sitemap
      socialImage:
        - '515'
      title:
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '0'
            -
              - template
              - 'Kino Klub'
        -
          __assoc__:
            -
              - key
              - jjw
            -
              - locked
              - '0'
            -
              - template
              - ' | A community of fellow motion picture lovers'
      titleSuffix: null
      twitterHandle: ''
system:
  edition: solo
  live: true
  name: 'Kino Klub'
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: Europe/Ljubljana
