defaultPlacement: beginning
enableVersioning: true
handle: events
name: Events
propagationMethod: all
siteSettings:
  7dff5ce0-6641-40f0-926b-8bd7f905d8bf: # Kino Klub SI
    enabledByDefault: true
    hasUrls: true
    template: novica.twig
    uriFormat: '{slug}'
  548d1972-4fd4-483a-9f1e-722e249ba366: # Kino Klub EN
    enabledByDefault: true
    hasUrls: true
    template: note.twig
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 174ece1f-7f5c-4c21-a167-7ce75a0c12fc
type: structure
