defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  7dff5ce0-6641-40f0-926b-8bd7f905d8bf: # Kino Klub SL
    enabledByDefault: true
    hasUrls: true
    template: index-sl.twig
    uriFormat: __home__
  548d1972-4fd4-483a-9f1e-722e249ba366: # Kino klub EN
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
