defaultPlacement: beginning
enableVersioning: true
handle: projects
name: Projects
propagationMethod: all
siteSettings:
  7dff5ce0-6641-40f0-926b-8bd7f905d8bf: # Kino Klub SI
    enabledByDefault: true
    hasUrls: true
    template: o-nas.twig
    uriFormat: '{slug}'
  548d1972-4fd4-483a-9f1e-722e249ba366: # Kino Klub EN
    enabledByDefault: true
    hasUrls: true
    template: about.twig
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: e3cba8a1-cc2e-4700-9a51-42510539ad04
type: structure
